### ISSUE TITLE
Use a Python package boilerplate

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/xai4chem#1]
This repository should have the structure of a Python package. @HellenNamulinda you can gain inspiration from other Ersilia repositories such as [lazy-qsar](https://github.com/ersilia-os/lazy-qsar) or [stylia](https://github.com/ersilia-os/stylia).

In short, I typically like to have:
* A `src` or `xai4chem` folder where the package code resides.
* A `notebooks` folder where I do my analyses and data processing
* A `scripts` folder where I have executable pipelines, also for analyses.
* An `assets` folder where I keep image files etc.
* A `data` folder
* A `results` folder
* All the necessary files, for example, a `setup.py`, a `LICENSE`, etc.

**Comment by miquelduranfrigola** [comment]
Hi @HellenNamulinda I have quickly had a look and it looks good to me. Feel free to close the issue or leave it open.

**Comment by HellenNamulinda** [comment]
I will close this

**Comment by miquelduranfrigola** [comment]
Hi @HellenNamulinda 
I've quickly checked the `setup.py` file. I think the `classifiers` are not yet specified. We can start from `python 3.10` in my opinion. Also, the keywords are somewhat redundant: `explainable ai` is equivalent to `xai`. Also, please check consistency between having a hyphen or not. Why `drug-discovery` has a hyphen and `machine learning` doesn't? Just pick a rule (hyphen or not hyphen) and stick to it.

**Comment by HellenNamulinda** [comment]
@miquelduranfrigola,
I will adjust those in the next PR.

**Comment by HellenNamulinda** [comment]
This was  addressed in the commit: https://github.com/ersilia-os/xai4chem/commit/adff61ccb69b42397ee53dd1b0154abc2e475c2d
