### ISSUE TITLE
MMV dataset, privacy preserving

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/xai4chem#4]
Hi @GemmaTuron and @HellenNamulinda 

We need to define a strategy to transfer the MMV dataset to @HellenNamulinda , ensuring that it is not accessible from GitHub since the dataset is still embargoed.

I suggest that we keep the dataset in our shared Google Drive folder related to Hellen's MSc project. For completeness, I would keep both the classification dataset (200k molecules) and the regression dataset (i.e. the one we need to use in this project).

@GemmaTuron, can you take care of this? Thanks!

**Comment by GemmaTuron** [comment]
This is done.
